# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets
import phonebook

class Ui_addDialog(object):

    def setupUi(self, addDialog):
        addDialog.setObjectName("addDialog")
        addDialog.resize(310, 535)
        addDialog.setMinimumSize(QtCore.QSize(310, 535))
        addDialog.setMaximumSize(QtCore.QSize(310, 535))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        addDialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image/favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        addDialog.setWindowIcon(icon)
        self.confirmButton = QtWidgets.QPushButton(addDialog)
        self.confirmButton.setGeometry(QtCore.QRect(50, 490, 93, 28))
        self.confirmButton.setAutoDefault(True)
        self.confirmButton.setObjectName("confirmButton")
        self.cancleButton = QtWidgets.QPushButton(addDialog)
        self.cancleButton.setGeometry(QtCore.QRect(170, 490, 93, 28))
        self.cancleButton.setObjectName("cancleButton")
        self.radioButton_man = QtWidgets.QRadioButton(addDialog)
        self.radioButton_man.setGeometry(QtCore.QRect(130, 140, 51, 19))
        self.radioButton_man.setObjectName("radioButton_man")
        self.radioButton_man.setChecked(True)
        self.radioButton_women = QtWidgets.QRadioButton(addDialog)
        self.radioButton_women.setGeometry(QtCore.QRect(200, 140, 51, 19))
        self.radioButton_women.setObjectName("radioButton_women")
        self.idlabel = QtWidgets.QLabel(addDialog)
        self.idlabel.setGeometry(QtCore.QRect(50, 40, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.idlabel.setFont(font)
        self.idlabel.setObjectName("idlabel")
        self.namelabel = QtWidgets.QLabel(addDialog)
        self.namelabel.setGeometry(QtCore.QRect(50, 90, 41, 16))
        self.namelabel.setObjectName("namelabel")
        self.sexlabe = QtWidgets.QLabel(addDialog)
        self.sexlabe.setGeometry(QtCore.QRect(50, 140, 41, 16))
        self.sexlabe.setObjectName("sexlabe")
        self.agelabel = QtWidgets.QLabel(addDialog)
        self.agelabel.setGeometry(QtCore.QRect(50, 190, 41, 16))
        self.agelabel.setObjectName("agelabel")
        self.bornlabel = QtWidgets.QLabel(addDialog)
        self.bornlabel.setGeometry(QtCore.QRect(50, 240, 72, 15))
        self.bornlabel.setObjectName("bornlabel")
        self.phonelabel = QtWidgets.QLabel(addDialog)
        self.phonelabel.setGeometry(QtCore.QRect(50, 290, 72, 15))
        self.phonelabel.setObjectName("phonelabel")
        self.emaillabel = QtWidgets.QLabel(addDialog)
        self.emaillabel.setGeometry(QtCore.QRect(50, 340, 72, 15))
        self.emaillabel.setObjectName("emaillabel")
        self.homelabel = QtWidgets.QLabel(addDialog)
        self.homelabel.setGeometry(QtCore.QRect(50, 390, 72, 15))
        self.homelabel.setObjectName("homelabel")
        self.professlabel = QtWidgets.QLabel(addDialog)
        self.professlabel.setGeometry(QtCore.QRect(50, 440, 41, 16))
        self.professlabel.setObjectName("professlabel")
        self.idlineEdit = QtWidgets.QLineEdit(addDialog)
        self.idlineEdit.setGeometry(QtCore.QRect(130, 40, 131, 21))
        self.idlineEdit.setObjectName("idlineEdit")
        self.namelineEdit = QtWidgets.QLineEdit(addDialog)
        self.namelineEdit.setGeometry(QtCore.QRect(130, 90, 131, 21))
        self.namelineEdit.setObjectName("namelineEdit")
        self.borndateEdit = QtWidgets.QDateEdit(addDialog)
        self.borndateEdit.setGeometry(QtCore.QRect(130, 240, 121, 22))
        self.borndateEdit.setObjectName("borndateEdit")
        self.phonelineEdit = QtWidgets.QLineEdit(addDialog)
        self.phonelineEdit.setGeometry(QtCore.QRect(130, 290, 131, 21))
        self.phonelineEdit.setObjectName("phonelineEdit")
        self.emaillineEdit = QtWidgets.QLineEdit(addDialog)
        self.emaillineEdit.setGeometry(QtCore.QRect(130, 340, 131, 21))
        self.emaillineEdit.setObjectName("emaillineEdit")
        self.homelineEdit = QtWidgets.QLineEdit(addDialog)
        self.homelineEdit.setGeometry(QtCore.QRect(130, 390, 131, 21))
        self.homelineEdit.setObjectName("homelineEdit")
        self.agespinBox = QtWidgets.QSpinBox(addDialog)
        self.agespinBox.setGeometry(QtCore.QRect(130, 190, 71, 22))
        self.agespinBox.setObjectName("agespinBox")
        self.professcomboBox = QtWidgets.QComboBox(addDialog)
        self.professcomboBox.setGeometry(QtCore.QRect(130, 440, 131, 22))
        self.professcomboBox.setObjectName("professcomboBox")
        self.professcomboBox.addItem("")
        self.professcomboBox.addItem("")
        self.professcomboBox.addItem("")
        self.professcomboBox.addItem("")

        self.retranslateUi(addDialog)
        self.cancleButton.clicked['bool'].connect(addDialog.close)
        QtCore.QMetaObject.connectSlotsByName(addDialog)
        fun=phonebook.fun()
        self.confirmButton.clicked.connect(lambda: fun.addStudent(
            self.idlineEdit.text(),
            self.namelineEdit.text(),
            self.radioButton_man,
            self.radioButton_women,
            self.agespinBox.value(),
            self.borndateEdit.text(),
            self.phonelineEdit.text(),
            self.emaillineEdit.text(),
            self.homelineEdit.text(),
            self.professcomboBox.currentText(),
            addDialog
        ))

    def retranslateUi(self, addDialog):
        _translate = QtCore.QCoreApplication.translate
        addDialog.setWindowTitle(_translate("addDialog", "添加学生信息"))
        self.confirmButton.setText(_translate("addDialog", "添加"))
        self.cancleButton.setText(_translate("addDialog", "取消"))
        self.radioButton_man.setText(_translate("addDialog", "男"))
        self.radioButton_women.setText(_translate("addDialog", "女"))
        self.idlabel.setText(_translate("addDialog", "学号"))
        self.namelabel.setText(_translate("addDialog", "姓名"))
        self.sexlabe.setText(_translate("addDialog", "性别"))
        self.agelabel.setText(_translate("addDialog", "年龄"))
        self.bornlabel.setText(_translate("addDialog", "出生日期"))
        self.phonelabel.setText(_translate("addDialog", "手机号码"))
        self.emaillabel.setText(_translate("addDialog", "电子邮箱"))
        self.homelabel.setText(_translate("addDialog", "家庭住址"))
        self.professlabel.setText(_translate("addDialog", "专业"))
        self.professcomboBox.setItemText(0, _translate("addDialog", "计算机科学与技术"))
        self.professcomboBox.setItemText(1, _translate("addDialog", "信息安全"))
        self.professcomboBox.setItemText(2, _translate("addDialog", "网络工程"))
        self.professcomboBox.setItemText(3, _translate("addDialog", "电子科学与技术"))